### ISSUE TITLE
Using Libcamera for Single Frame capture from two cameras on the RPI4 Compute Module

### ISSUE THREAD

**Issue by reshuler** [Qengineering/Libcamera-OpenCV-RPi-Bullseye-64OS#2]
What about using Libcamera to capture a signal frame image from two different cameras that are trigger milliseconds apart via OpenCV and RPI4 Compute Module?

Thanks,
Robert

**Comment by Qengineering** [comment]
It will be a real nightmare. Synchronizing the frames from different sources and with different capture devices. Even more because the RPi camera has a rolling shutter and no external trigger input.
Better to use a camera with an external trigger. Or even better, [this stereo camera](https://www.arducam.com/product/b0195-synchronized-stereo-camera-hat-raspberry-pi/) or [this one](https://www.arducam.com/product/arducam-1mp2-wide-angle-stereo-camera-for-raspberry-pi-jetson-nano-and-xavier-nx-dual-ov9281-monochrome-global-shutter-camera-module/) for the RPi.

**Comment by reshuler** [comment]
Thanks
