### ISSUE TITLE
GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

### ISSUE THREAD

**Issue by wineos** [Qengineering/Libcamera-OpenCV-RPi-Bullseye-64OS#4]
I am using python3 on raspberry pi.

I executed the following codes and reported the warning message:

import cv2
import os
import usb

if os.path.exists("/home/pi/MMRS/camA.png"):    
    os.remove("/home/pi/MMRS/camA.png")

camera1 = cv2.VideoCapture(0)
return_value, image = camera1.read()
cv2.imwrite('/home/pi/MMRS/camA.png', image)
del(camera1)

Can anyone help to fix it?  Thank you so much!

**Comment by Qengineering** [comment]
Dear @wineos,

Before we can help you, we need more info.

Which Debian distribution do you use? Buster (Debian 10) of Bullseye (Debian 11)?
The later doesn't support VideoCapture() any more, by the way.

Which warnings did you recieve?

**Comment by wineos** [comment]
Dear Qengineering,

Oh, I am using Bullseye version, 64-bit, with OpenCV 4.5.5.

I am new on all these tools, so I don't know Bullseye doesn't support VideoCapture() anymore.

Can you give me advice?  How can I rewrite it?

Thank you so much!

**Comment by Qengineering** [comment]
Dear @wineos 

I've some sad news. We don't use Python here at the office, only C++. We haven't any Python code available. 

Please see: https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/
Please see: https://core-electronics.com.au/guides/raspberry-pi-bullseye-camera-commands/

**Comment by Qengineering** [comment]
If you want to keep it simple and still enjoy the convenience of Python, switch back to the 'old' Buster OS and reinstall OpenCV.
Since Bullseye was only recently released, there isn't much documentation and code snippets. The difference between Buster and Bullseye is not that big. We still use Buster for our camera apps because ffmpeg doesn't support Bullseye either.
Especially as a beginner you should not get stuck on this kind of version misery.

**Comment by wineos** [comment]
Dear Qengineering,

Thank you for your information and advice.

I will then switch back to Buster OS.

Thank you so much!
